### ISSUE TITLE
stops all playing audio on ios

### ISSUE THREAD

**Issue by extrawurst** [NiklasEi/bevy_kira_audio#118]
For games this is often not the desired behaviour, as people might wanna mute the games internal audio and listen to spotify, podcast or whatever still while playing.

I wonder if we can expose this as an option somehow, no idea how deep this goes: bevy_kira, kira itself or cpal

**Comment by extrawurst** [comment]
a quick fix for anyone stumbling across this:

```
#import "bindings.h"
#import "AVFAudio/AVAudioSession.h"

int main() {
    [[AVAudioSession sharedInstance] setCategory: AVAudioSessionCategoryAmbient error: nil];
    main_rs();
    return 0;
}
```

**Comment by NiklasEi** [comment]
Nice, good to know. Would you like to open a PR for that?

**Comment by eugenehp** [comment]
FYI: made bindings for [avfaudio](https://crates.io/crates/avfaudio)

```rust
use avfaudio::session::{AVAudioSession, Category};

pub fn main() {
    let shared_instance = AVAudioSession::shared_instance();
    shared_instance.set_category(Category::ambient());
}
```

**Comment by extrawurst** [comment]
@eugenehp nice! I was hoping for icrates to eventually come around supporting `AVAudioSession`

**Comment by NiklasEi** [comment]
Did I understand correctly that this would be something the application (e.g., bevy_game_template) would configure if other audio is supposed to overlap instead of stop? In that case, I will close this issue but would love a PR to bevy_game_template as I don't have access to an iOS device myself.
Feel free to open the issue again if I misunderstood.
