### ISSUE TITLE
SpatialAudio does not respect AudioChannel settings

### ISSUE THREAD

**Issue by tpuric** [NiklasEi/bevy_kira_audio#123]
When playing SpatialAudio sounds, they do not respect their AudioChannel settings such as volume.

It also does not apply to individual controls such as `audio.play(...).set_volume(0.5);`

We're attempting to add master/channel controls for the end user but SpatialAudio does not adhere to these settings.

**Comment by NiklasEi** [comment]
Yeah, there is no combining of volumes at the moment. Since spacial audio changes the volume based on the distance of emitter and listener any other volume will be overwritten with the first frame.

As a heads up: I think that this plugin will be archived with the next couple of Bevy versions. It was intended as a try out for Kira in Bevy and there currently is a working group changing the audio backend in Bevy to Kira. So it kinda has served it's purpose. I will continue to update to new Bevy versions until the new Bevy audio is there and stable, but I don't expect much feature work in here during that period.

**Comment by tpuric** [comment]
That's perfectly reasonable. We'll just move forward without this feature and contribute if it's vital.

Thank you very much for the library, it's been very pleasant to work with. Feel free to close
