### ISSUE TITLE
Strange issue with latest bevy main

### ISSUE THREAD

**Issue by VisualDevelopment** [NiklasEi/bevy_kira_audio#31]
```
error[E0277]: the trait bound `AudioSource: TypeUuid` is not satisfied
  --> src/states/mod.rs:8:22
   |
8  |     pub loop_handle: Handle<AudioSource>,
   |                      ^^^^^^^^^^^^^^^^^^^ the trait `TypeUuid` is not implemented for `AudioSource`
   |
   = note: required because of the requirements on the impl of `Asset` for `AudioSource`
note: required by a bound in `bevy::prelude::Handle`
  --> /Users/visual/.cargo/git/checkouts/bevy-f7ffde730c324c74/91c3b21/crates/bevy_asset/src/handle.rs:65:8
   |
65 |     T: Asset,
   |        ^^^^^ required by this bound in `bevy::prelude::Handle`

For more information about this error, try `rustc --explain E0277`.
```

**Comment by NiklasEi** [comment]
To be sure: you are using the `bevy_main` branch and Bevy's `bevy_audio` and `mp3` features are disabled?

**Comment by VisualDevelopment** [comment]
![image](https://user-images.githubusercontent.com/30368284/140271429-95c0b9b8-01ca-4c17-bd1a-6e8238b8bc1f.png)

**Comment by NiklasEi** [comment]
Could you try pinning Bevy to the same commit than bevy_kira_audio does?
The `bevy_main` branch uses `
bevy = { git = "https://github.com/bevyengine/bevy", rev = "6a8a8c9d21f32e0e46623db9438813b009f9e014" }`.

**Comment by VisualDevelopment** [comment]
That works, but, that restricts me to use that specific commit

**Comment by NiklasEi** [comment]
If there are no further breaking changes since that commit, you should be able to patch the bevy dependency from the official repository to your own fork in your Carge file. Then bevy_kira_audio will use the latest commit, too.

**Comment by VisualDevelopment** [comment]
This issue might be resolved if you update the bevy revision
![image](https://user-images.githubusercontent.com/30368284/140277599-2bb6539a-2b4f-4cba-8936-8d68cab90ff1.png)
![image](https://user-images.githubusercontent.com/30368284/140277704-176aad9d-8222-4914-9e46-6e98d2d8330e.png)

**Comment by VisualDevelopment** [comment]
Also, I recommend reading https://bevy-cheatbook.github.io/setup/bevy-git.html

**Comment by VisualDevelopment** [comment]
Yes, if you update to latest bevy main the issue is fixed.
![image](https://user-images.githubusercontent.com/30368284/140281954-ffdf096e-1f3d-4f7b-ba22-bbc3d151b3e6.png)
@NiklasEi

**Comment by NiklasEi** [comment]
I choose on purpose to pin the Bevy dependency because I want the branch to always work. See #13 for the last time this came up.

An alternative I have been considering is to depend on the main branch without pinning a working revision and have some workflow regularly check if all tests are still green. But for now I would like keep pinning working revisions.

**Comment by NiklasEi** [comment]
I will close this for now, because the used Bevy commit can be patched in the user's `Cargo.toml` file. You can also patch the Bevy dependency to use the latest Bevy `main` commit, which means you don't have to update the reference all the time.

I also updated the Bevy commit on the `bevy_main` branch.
