### ISSUE TITLE
audio_output.instances not cleaned up properly

### ISSUE THREAD

**Issue by Elogain** [NiklasEi/bevy_kira_audio#46]
I stress tested an application Im making (for fun really) and it plays audio. Due to the high volume of play commands added I started to get log messages that I think originates from the CommandQueueFull error (perhaps kira printed it?). 

I did a profiling and ran the stress test and basically even long after all audio stops playing this method:
https://github.com/NiklasEi/bevy_kira_audio/blob/a08ee2a4e3719cfbffbbca5f3feb61690e2233c6/src/audio_output.rs#L454
continues to take up in the profiling I did 34-35ms of frame-time (steadily growing from almost no time at start of app then really going haywire after a while). My guess is that the cleanup_stopped_instances don't detect them as faulty or even started but they still exist in the vector or something.

**Comment by ramirezmike** [comment]
I might be running into a similar issue...

I see a number of these messages
> Failed to set volume for instance: CommandQueueFull

and then a panic on 

> thread 'main' panicked at 'Failed to add sound to the AudioManager: CommandProducerError(CommandQueueFull)', bevy_kira_audio-ec9a44b32a5309c9/85658f1/src/audio_output.rs:75:14

It seems exactly like what's mentioned in #17 actually.. I might not be quite on latest on this project since its targeting bevy 0.6.1

**Comment by Elogain** [comment]
You might be hit by stuff that has been "fixed" since then as you are using 0.6.1, I see a bit of refactoring in the CommandQueueFull places since 0.6.1 compat. Still seems to be some bad instances not being cleaned up still.

**Comment by NiklasEi** [comment]
I will take a look at this again after #48 
Thank you for pointing out the problem :slightly_smiling_face:

**Comment by NiklasEi** [comment]
I stress-tested `main` by playing two sounds per frame on two channels.
1. The instances in the plugin's resource get cleaned up properly
2. I could run the app for ~10min before shutting it down
3. On one attempt I got an error from Kira saying that there was no more space for sound after a couple of minutes

**Comment by Elogain** [comment]
Oh, I was probably adding 100's of sounds in one channel per frame. It must def be some instances here:
https://github.com/NiklasEi/bevy_kira_audio/blob/a08ee2a4e3719cfbffbbca5f3feb61690e2233c6/src/audio_output.rs#L459
(as that system took 34-35ms, I'd guess quite the few actually)
that wasn't properly cleaned up in: [cleanup_stopped_instances](https://github.com/NiklasEi/bevy_kira_audio/blob/a08ee2a4e3719cfbffbbca5f3feb61690e2233c6/src/audio_output.rs#L356)

It might be that the list of instances that hasn't been stopped and possibly are in a bad state due to the massive amounts that were trying to be added, I've let the app run for quite the bit to see if that list was ever drained but it didnt seem so.

Q: did you do it after updating Kira now? If so I can see if I can get latest bevy_kira_audio if/when you release it and re-do my test :)

**Comment by Elogain** [comment]
Actually, go to 1:50:ish in this video and you can see what I mean by adding a non-sane amount of audio https://www.youtube.com/watch?v=bTj6nkgYDl

**Comment by NiklasEi** [comment]
The video does not seem to be available anymore, but I think I saw it on Discord (if I am thinking about the correct showcase).

I see that the 2 sounds per frame were way too little for a decent stress test. There is now a `stress_test` example on `main`. I can play around 75 (short) sounds per frame on my machine without getting any underrun or errors (it requires adjusting the audio backend settings though).

Running this example on version 0.9, I can reproduce the issue that instances don't get cleaned up properly. This works fine on `main`, so I would consider the issue closed with the next release.

Please correct me if I am wrong, but playing multiple instances of the same sound in the same frame is quite useless as it only increases the amplitude of the sound. In `bevy_kira_audio` 0.9 only one instance of the sound would actually play because Kira v5 had [a cooldown on sounds by default](https://github.com/tesselode/kira/blob/v0.5.3/kira/src/sound/settings.rs#L104). So effectively you were probably not playing so many sounds every frame in your game. As far as I can see, this cooldown option is gone in Kira v6. I would be interested to see the difference when you upgrade.

**Comment by Elogain** [comment]
I can change bevy kira to point at master on github and re-test :) Lets hold thumbs that its fixed for next release.

**Comment by Elogain** [comment]
"Please correct me if I am wrong, but playing multiple instances of the same sound in the same frame is quite useless as it only increases the amplitude of the sound. " Yes, but unless I add an reduce system that takes one frames request of  "play this audio please" and reduce a number of these requests to "play it once, but with volume * the requests" then thats how the nature of "thing x happens -> please play its corresponding audio" will be like out of the box :)

**Comment by NiklasEi** [comment]
It should be resolved in the just-published version 0.10

**Comment by Elogain** [comment]
Heya! Am about to upgrade, will try a stress-test later and report back if still wonky :) Closing this for now! Thanks for your work :)
